### ISSUE TITLE
Patch Request : Gargoyles MD +

### ISSUE THREAD

**Issue by Bunnnyface** [Infinest/Streets-of-Rage-1-MD-Plus#2]
Hello Infinest !
I know it is not the right place to ask you this but I don't know how to contact you otherwise.

Since you patched SoR and some other games,
would you be interested in patching the Gargoyles genesis game ?

You can check that ArcadeTV is too busy to do it right now, via this post :
https://www.zeldix.net/t2759-gargoyles-md-1995-with-remastered-version

I can provide files of the game and the soundtrack as .wav.
Unfortunately, I don't know genesis games coding and I have no clue where to start.

I hope I don't bother you with my request so don't hesitate to tell me if it's the case.
Have a good day !

**Comment by Infinest** [comment]
Hey there! You can always contact me on my [Twitter](https://twitter.com/infinest).

The lack of good debugging tools for the Megadrive kind of made me lose interest so i haven't worked on on Megadrive stuff in quite a while. I'm probably very rusty at it but since the source code is available i will take a look at it.
Not gonna make any promises yet though.

I don't need any sound files just yet since I can just test with the sound files of a different MD+ game.
The other stuff (ROM, source code) I already got myself.

Don't worry about bothering me.👍It costs nothing to ask.
I will get back to you in a bit!

**Comment by Bunnnyface** [comment]
Thank you for your response !
I am not a twitter user so I allowed myself to contact you here.
Of course you are not obliged to do anything so no pressure, take your time and it's ok if you put the making of this patch aside.
I will follow this thread for updates.

Thank's again for your time !

**Comment by Infinest** [comment]
Here's the repository for the Gargoyles MD+ patch: [https://github.com/Infinest/Gargoyles-MD-Plus](https://github.com/Infinest/Gargoyles-MD-Plus)
It contains the code for the first fully working version of the patch. Of course there may still be bugs because i have not played through the entirety of the game. That would be your job. ^^

Do you happen to have Discord or any way i can privately supply you test builds?

At this point it would probably be good to have the proper wave files and cue sheet for further testing as well.
I highly suggest you get Relikk from Zeldix onboard for that, even if you have put them together already by yourself.
He's really good at fine tuning these files.

For the cue sheet this information from patch.asm is going to be interesting:

```
	_MUS_Castle:					        equ	$3C ; CUE: 01 Sound test: 04 | LOOP
	_MUS_Rookery:					equ	$3E ; CUE: 02 Sound test: 05 | LOOP
	_MUS_Subway:					equ	$40 ; CUE: 03 Sound test: 07 | LOOP
	_MUS_Titlepage:					equ	$41 ; CUE: 04 Sound test: 03 | LOOP
	_MUS_Rooftops:					equ	$42 ; CUE: 05 Sound test: 06 | LOOP
	_MUS_Continue:					equ	$43 ; CUE: 06 Sound test: 10 | LOOP
	_MUS_Forge:						equ	$44 ; CUE: 07 Sound test: 08 | LOOP
	_MUS_Boss:						equ	$45 ; CUE: 08 Sound test: 00 | LOOP
	_MUS_GameOver:					equ	$46 ; CUE: 09 Sound test: 01 | NO LOOP
	_MUS_Hammer:					equ	$47 ; CUE: 10 Sound test: 02 | NO LOOP
	_MUS_StoryScreen:				        equ	$48 ; CUE: 11 Sound test: 09 | LOOP
```

Cue equals the index of the track in the cue sheet. Sound test equals the index of the track within the ingame sound test.
LOOP and NO LOOP defines whether the track should loop or not.

**Comment by Bunnnyface** [comment]
Wow, you are very reactive !
Yes, I use Discord but I don't know how to share my id safely here.

I am going to share this thread on Zeldix here :
https://www.zeldix.net/t2759-gargoyles-md-1995-with-remastered-version

Relikk is already in the conversation so it will be simple to communicate.

Thank you very much for your help !
